#!/bin/bash

usage="k8s-nodes-status <env>"
notes="calls 'kubectl top node' on all nodes in the cluster for the given env"

# reads "env" param, loads "namespace" param
. ./load-config.sh

kubectl get nodes | grep 'node\|master' | awk '{print $1}' | xargs -I {} kubectl top node {}