#!/bin/bash

usage="k8s-tail <env> <pod_names_to_grep>"
notes='can optionally add additional params, such as "--since=5m"'

pod_names=$2
since=$3

# reads "env" param, loads "namespace" param
. "$(dirname "${BASH_SOURCE[0]}")/load-config.sh"

kubectl --namespace=$namespace get pods | grep $pod_names | cut -f 1 -d ' ' | xargs -P 20 -I {} kubectl --namespace=$namespace logs -f {} $since
