#!/bin/bash

usage="k8s-pod-grep <env> <pod_names_to_grep> <grep_string>"
notes="reports count of case-insensitive grep string per pod, over the last 5 minutes"

pod_names=$2
grep_string=$3

# reads "env" param, loads "namespace" param
. ./load-config.sh

for pod in $(kubectl --namespace=$namespace get pods | grep "$pod_names" | cut -f 1 -d ' '); do
    grep_count=$(kubectl --namespace=$namespace logs $pod --since=5m | grep -i "$grep_string" | wc -l)
    echo "pod = $pod, grep count = $grep_count"
done