#!/bin/bash

usage="k8s-top-nodes <env>"
notes="calls 'kubectl top node' on all nodes in the cluster for the given env"

# reads "env" param, loads "namespace" param
. "$(dirname "${BASH_SOURCE[0]}")/load-config.sh"

kubectl get nodes | grep 'node\|master' | awk '{print $1}' | xargs -I {} kubectl top node {}
