#!/bin/bash

usage="k8s-pod-errors <env> <pod_names_to_grep>"
notes="greps for case-insentitive 'error' string over the last 5 minutes"

pod_names=$2

# reads "env" param, loads "namespace" param
. ./load-config.sh

for pod in $(kubectl --namespace=$namespace get pods | grep $pod_names | cut -f 1 -d ' '); do
    error_count=$(kubectl --namespace=$namespace logs $pod --since=5m | grep -i error | wc -l)
    echo "pod = $pod, error count = $error_count"
done
