#!/bin/bash

usage="k8s-pod-errors <env> <pod_names_to_grep>"
notes="greps for case-insentitive 'error' string over the last 5 minutes. Can optionally add additional param like '10m' or '24h' to change the --since= value."

pod_names=$2
since="${3:-5m}"

# reads "env" param, loads "namespace" param
. "$(dirname "${BASH_SOURCE[0]}")/load-config.sh"

for pod in $(kubectl --namespace=$namespace get pods | grep $pod_names | cut -f 1 -d ' '); do
    error_count=$(kubectl --namespace=$namespace logs $pod --since=$since | grep -ai 'error' | wc -l)
    echo "pod = $pod, error count = $error_count"
done
